#yify.tv domain
yifytv: http://yify.tv

#view47.com domain
view47: http://view47.com

#123movies.to domain
onetwothree: http://123movies.to

#reddit subs
#you are free to add your own
reddit:
  - fullmoviesonyoutube
  - fullforeignmovies

#youtube channel id's or playlist id's (comment is optional)
youtube:
  - UCSMOQeBJ2RAnuFungnQOxLg #BlenderFoundation
  - PL6B3937A5D230E335 #Blender Open Movies

#enable or disable subtitles
subtitles: false

#what language you want your subtitles in
#go here:
#https://github.com/aetheon/node-opensubtitles-client/blob/master/langs.dump.txt
#and search for your language alias if you are unsure
subtitle_lang: eng

#player executable
player: vlc

#here is where you need to enter the command for loading subtitles into your player
#for vlc its --sub-file=
#for mpv its --sub-file=
player_sub_cmd: --sub-file=

#Here is where you can pass any arguments to your player of choice
#For example on vlc you might want to pass --file-caching="<ms>" --network-caching="<ms>"
#To raise the ammount of network buffer
player_arg_cmd:

#download location (absolute path) (with trailing slash)
#ex: download_location: /home/geewiz/Videos/
#If you dont set this it wont ask you if you want to download the file
download_location:
